# Numpy

Numpy, dizilerle çalışmak için kullanılır. Bunun yanında doğrusal cebir, matris gibi alanlarda kullanılır.

Yapı ve işlev olarak listelerle benzer olsada listelerden çok daha hızlıdırlar.

In [1]:
#pip install numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

In [5]:
#Tüm değerleri aynı veri tipine dönüştürür.
arr = np.array([3,15.4,8,6.7])
arr

array([ 3. , 15.4,  8. ,  6.7])

**Data Type**

In [6]:
arr.dtype

dtype('float64')

In [7]:
#Dönüştürmek istediğimiz veri tipini belirtebiliriz.
arr2 = np.array([3,15.4,8,6.7,2.18,5],dtype="int")
arr2

array([ 3, 15,  8,  6,  2,  5])

In [8]:
arr2.dtype

dtype('int32')

In [9]:
array = np.array([1,8.7,6.3,4],dtype="str")
array

array(['1', '8.7', '6.3', '4'], dtype='<U3')

## Dizilerdeki Boyutlar

**0-D Arrays (Sıfır Boyutlu Diziler)**

Bir dizideki öğelerdir. Bir dizideki her değer sıfır boyutlu dizidir.

In [10]:
np.array(36)

array(36)

**1-D Arrays (Bir Boyutlu Diziler)**

Sıfır boyutlu dizileri olan bir diziye bir boyutlu dizi denir.

In [11]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

**2-D Arrays (İki Boyutlu Diziler)**

Bir boyutlu dizileri olan bir diziye iki boyutlu dizi denir. İki boyutlu diziler matrislerdir.

In [12]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

**3-D Arrays (Üç Boyutlu Diziler)**

İki boyutlu dizileri olan bir dizeye üç boyutlu dizi denir.

In [13]:
np.array([[[1,2,3],[4,5,6]],
          [[9,8,7],[6,5,4]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [14]:
array1=np.array(36)
array2=np.array([1,2,3,4])
array3=np.array([[1,2,3],[4,5,6], [7,8,9]])
array4=np.array([[[1,2,3],[4,5,6]],[[9,8,7],[6,5,4]]])

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

0
1
2
3


In [15]:
#ndmin ile oluşturulan arrayin boyutunu belirlenir
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

**Indexing**

In [16]:
#1-D
array2

array([1, 2, 3, 4])

In [17]:
array2[2]

3

In [18]:
#2-D
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#1.satırdaki 2. elemana ulaşalım
array3[0,1]

2

In [20]:
#2.satırdaki 3.elemana ulaşalım
array3[1,2]

6

In [21]:
###3.satırdaki 1.elemana ulaşalım
array3[2,0]

7

In [22]:
#3-D
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [23]:
array4[0,1,1]

5

In [24]:
array4[1,0,2]

7

**Slicing**

In [25]:
#1-D
array2

array([1, 2, 3, 4])

In [26]:
array2[2:]

array([3, 4])

In [27]:
array2[:3]

array([1, 2, 3])

In [28]:
#2-D
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array3[0:2,2]

array([3, 6])

In [30]:
array3[1:,0:2]

array([[4, 5],
       [7, 8]])

In [31]:
array3[:,1]

array([2, 5, 8])

In [32]:
array3[:,-1]

array([3, 6, 9])

In [33]:
array3[2,:]

array([7, 8, 9])

In [34]:
#3-D
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [35]:
array4[0,:,1:]

array([[2, 3],
       [5, 6]])

In [36]:
array4[0,1,:]

array([4, 5, 6])

In [37]:
array4[1,1,0:2]

array([6, 5])

In [38]:
array4[1,:,0:2]

array([[9, 8],
       [6, 5]])

## Temel Numpy Özellikleri

**Size**

In [39]:
#Size, arrayde bulunan eleman sayısını verir.
print(array2)
print(array2.size)

[1 2 3 4]
4


In [40]:
print(array3)
print(array3.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [41]:
print(array4)
print(array4.size)

[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]]
12


**Shape**

In [42]:
array2

array([1, 2, 3, 4])

In [43]:
#1-D arraylerde arrayin içerdiği eleman sayısı bilgisini verir.
np.shape(array2)

(4,)

In [44]:
np.shape(np.array([12,5,6,45,9]))

(5,)

In [45]:
#2-D arraylerde boyut,arrayin satır ve sütun sayısı bilgisini verir.
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.shape(array3)

(3, 3)

In [47]:
new_array = np.array([[11,6,35,14,47],[7,94,72,18,49],[32,5,14,21,8]])
new_array

array([[11,  6, 35, 14, 47],
       [ 7, 94, 72, 18, 49],
       [32,  5, 14, 21,  8]])

In [48]:
np.shape(new_array)

(3, 5)

In [49]:
#3-D arraylerde katman,satır ve sütun bilgisi verir.
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [50]:
np.shape(array4)

(2, 2, 3)

In [3]:
new_array = np.array([[[12,54],[47,35],[11,28]],
                      [[64,99],[74,27],[86,41]],
                      [[96,53],[74,61],[58,26]]])
new_array

array([[[12, 54],
        [47, 35],
        [11, 28]],

       [[64, 99],
        [74, 27],
        [86, 41]],

       [[96, 53],
        [74, 61],
        [58, 26]]])

In [52]:
np.shape(new_array)

(3, 3, 2)

**Reshape**

In [53]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(np.shape(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [54]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [56]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [59]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [61]:
arr.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [62]:
arr.reshape(2,-1,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
#concatenate
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [66]:
b = np.array([[1,2,3,4],[4,5,6,7]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [67]:
np.concatenate([b,b],axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [68]:
np.concatenate([a,b])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [69]:
#Sıfırlardan oluşan bir array oluşturma
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [71]:
#Birlerden oluşan bir array oluşturma
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.ones(5,dtype="int")

array([1, 1, 1, 1, 1])

In [73]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [74]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
#np.arange(ilk değer, son değer, sayı aralığı)
np.arange(0,41,8)#np.arange(ilk değer, son değer, sayı aralığı)

array([ 0,  8, 16, 24, 32, 40])

In [77]:
np.array(np.linspace(0,1,10))

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [78]:
np.random.randint(10,size=(3,5))

array([[3, 3, 9, 6, 2],
       [7, 7, 2, 2, 9],
       [1, 0, 1, 9, 9]])

## İstatiksel Fonksiyonlar

In [79]:
array = np.array([12,8,5,19,5,7,13,5])
array

array([12,  8,  5, 19,  5,  7, 13,  5])

In [80]:
np.max(array)

19

In [81]:
np.min(array)

5

In [82]:
np.mean(array)

9.25

In [83]:
np.std(array)

4.710360920354193

**Matematiksel Fonksiyonlar**

In [84]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [85]:
b = np.array([2,5,6,8])
b

array([2, 5, 6, 8])

In [86]:
c = np.add(a,b)
c

array([12, 25, 36, 48])

In [87]:
d = np.multiply(a,b)
d

array([ 20, 100, 180, 320])

In [88]:
e = np.divide(a,b)
e

array([5., 4., 5., 5.])

In [89]:
f = np.dot(a,b)
f

620

In [93]:
########

In [94]:
array2

array([1, 2, 3, 4])

In [95]:
array2>6

array([False, False, False, False])

In [96]:
array2[array2>6]

array([], dtype=int32)

In [97]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
array3[array3>5]

array([6, 7, 8, 9])

In [99]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [100]:
array4[array4>6]

array([9, 8, 7])