# Pandas

In [3]:
pip install pandas


     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 330.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.8 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 404.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.5 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.1/11.5 MB 1.1 MB/s eta 0:00:11
    --------------------------------------- 0.2/11.5 MB 1.6 MB/s eta 0:00:08
    --------------------------------------- 0.2/11.5 MB 1.3 MB/s eta 0:00:09
   - -------------------------------------- 0.4/11.5 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.5/11.5 MB 1.9 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/11.5 MB 2.4 MB/s eta 0:00:05
   ---- ----------------------------------- 1.2/11.5 MB 3.1 MB/s eta 0:00:04
  

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
### Buaraya ödevi eklicem.
import pandas as pd

sozluk = {
    "Kategori": ["Giyim","Giyim", "Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
    "Ürün" : ["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
    "Fiyat" : [300,180,450,50,700,400,150,80,850,900]
}

data = pd.DataFrame(sozluk)


In [6]:
import pandas as pd

# Sample data
data = {"Kategori": ["Elektronik", "Moda", "Gıda", "Kitap"],
        "Ürün": ["Telefon", "Pantolon", "Makarna", "Roman"]}

# Create DataFrame
df = pd.DataFrame(data)

# Now you can access the value at index 2
kategori_2 = df.loc[2, "Kategori"]
print("2. indexte bulunan kategori:", kategori_2)

2. indexte bulunan kategori: Gıda


In [8]:
# Giyim kategorisindeki ürünler
giyim_urunleri = df[df["Kategori"] == "Giyim"]["Ürün"]
print("Giyim Ürünleri:\n", giyim_urunleri)

# Ayakkabı kategorisindeki ürünler
ayakkabi_urunleri = df[df["Kategori"] == "Ayakkabı"]["Ürün"]
print("Ayakkabı Ürünleri:\n", ayakkabi_urunleri)

# Aksesuar kategorisindeki ürünler
aksesuar_urunleri = df[df["Kategori"] == "Aksesuar"]["Ürün"]
print("Aksesuar Ürünleri:\n", aksesuar_urunleri)

Giyim Ürünleri:
 Series([], Name: Ürün, dtype: object)
Ayakkabı Ürünleri:
 Series([], Name: Ürün, dtype: object)
Aksesuar Ürünleri:
 Series([], Name: Ürün, dtype: object)


In [13]:
print(df.columns)

Index(['Kategori', 'Ürün'], dtype='object')


In [14]:
df["Fiyat"] = [100, 200, 350, 450]  # Example prices for your data

In [15]:
giyim_300_ust = df[(df["Kategori"] == "Giyim") & (df["Fiyat"] > 300)]
print("Giyim kategorisinde fiyatı 300'den fazla olan ürünler:\n", giyim_300_ust)

Giyim kategorisinde fiyatı 300'den fazla olan ürünler:
 Empty DataFrame
Columns: [Kategori, Ürün, Fiyat]
Index: []


In [16]:
# Giyim kategorisinde fiyatı 300'den fazla olan ürünler
giyim_300_ust = df[(df["Kategori"] == "Giyim") & (df["Fiyat"] > 300)]
print("Giyim kategorisinde fiyatı 300'den fazla olan ürünler:\n", giyim_300_ust)

# Ayakkabı kategorisinde fiyatı 600'den az olan ürünler
ayakkabi_600_alt = df[(df["Kategori"] == "Ayakkabı") & (df["Fiyat"] < 600)]
print("Ayakkabı kategorisinde fiyatı 600'den az olan ürünler:\n", ayakkabi_600_alt)

# Aksesuar kategorisinde fiyatı 100'den fazla olan aksesuarlar
aksesuar_100_ust = df[(df["Kategori"] == "Aksesuar") & (df["Fiyat"] > 100)]
print("Aksesuar kategorisinde fiyatı 100'den fazla olan ürünler:\n", aksesuar_100_ust)

Giyim kategorisinde fiyatı 300'den fazla olan ürünler:
 Empty DataFrame
Columns: [Kategori, Ürün, Fiyat]
Index: []
Ayakkabı kategorisinde fiyatı 600'den az olan ürünler:
 Empty DataFrame
Columns: [Kategori, Ürün, Fiyat]
Index: []
Aksesuar kategorisinde fiyatı 100'den fazla olan ürünler:
 Empty DataFrame
Columns: [Kategori, Ürün, Fiyat]
Index: []


Pandas kütüphanesi veriyi analiz etmek için kullanılır. Veri bilimi projelerinde,veri okuma, veri ön işleme gibi adımlarda kullanılır.
Pandasta en çok kullanılan veri yapılar Series ve DataFrame yapılarıdır.

**Seriler**

Seriler bir tablodaki sütunlar gibidir. Bir boyutlu arraylerdir.

In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
seri = pd.Series([12,47,34,66,50])
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
#index bilgisi verir
seri.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
#serideki eleman sayısını verir
seri.size

5

In [7]:
#boyut bilgisi verir
seri.ndim

1

In [8]:
#değerlere array formunda  erişmek istersek values methodunu kullanabiliriz
seri.values

array([12, 47, 34, 66, 50], dtype=int64)

In [9]:
#fonksiyonun içine girilen değer kadar veriyi gösterir
seri.head(3)

0    12
1    47
2    34
dtype: int64

In [10]:
seri.tail(3)

2    34
3    66
4    50
dtype: int64

In [11]:
#serilerde de indexing ve slicing işlemlerini yapabiliyoruz
seri[0]

12

In [12]:
seri[2]

34

In [13]:
seri[3]

66

In [14]:
seri[0:2]

0    12
1    47
dtype: int64

In [15]:
seri[1:4]

1    47
2    34
3    66
dtype: int64

In [16]:
#indexleri değiştirebilir,isimlendirme yapabiliriz
seri2 = pd.Series([15,45,63,85,41],index=[1,8,5,3,6])
seri2

1    15
8    45
5    63
3    85
6    41
dtype: int64

In [17]:
seri2[1]

15

In [18]:
seri2[5]

63

In [19]:
seri3 = pd.Series([15,45,63,85,41],index=["a","b","c","d","e"])
seri3

a    15
b    45
c    63
d    85
e    41
dtype: int64

In [20]:
seri3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
seri3["b"]

45

In [22]:
seri3["d"]

85

In [23]:
seri3["a":"d"]

a    15
b    45
c    63
d    85
dtype: int64

In [24]:
#sözlük üzerinden seri oluşturalım
sozluk = {"Ayşe":42,
          "Elif":27,
          "Fatma":36}
sozluk

{'Ayşe': 42, 'Elif': 27, 'Fatma': 36}

In [25]:
yeni_sozluk = pd.Series(sozluk)
yeni_sozluk

Ayşe     42
Elif     27
Fatma    36
dtype: int64

In [26]:
yeni_sozluk["Ayşe"]

42

In [27]:
#######################
import numpy as np
dizi = np.random.randint(50,size=6)
dizi

array([45, 22, 10, 18, 37, 32])

In [28]:
seri2 = pd.Series(dizi)
seri2

0    45
1    22
2    10
3    18
4    37
5    32
dtype: int32

In [29]:
seri2.index = ["a","b","c","d","e","f"]

In [30]:
seri2

a    45
b    22
c    10
d    18
e    37
f    32
dtype: int32

In [31]:
seri2[["b","d"]]

b    22
d    18
dtype: int32

In [32]:
seri2[["a","c","f"]]

a    45
c    10
f    32
dtype: int32

In [33]:
seri2[["b","d"]]=55
seri2

a    45
b    55
c    10
d    55
e    37
f    32
dtype: int32

**DataFrame**

In [34]:
pd.DataFrame(seri2)

0
a  45
b  55
c  10
d  55
e  37
f  32

In [35]:
pd.DataFrame(seri2,columns=["Sayılar"])

Sayılar
a       45
b       55
c       10
d       55
e       37
f       32

In [36]:
yeni_dizi=np.random.randint(25,size=12).reshape(4,3)
yeni_dizi

array([[19, 12, 16],
       [21,  1,  0],
       [16,  4, 22],
       [16,  0, 10]])

In [37]:
df = pd.DataFrame(yeni_dizi,columns=["col1","col2","col3"])
df

col1  col2  col3
0    19    12    16
1    21     1     0
2    16     4    22
3    16     0    10

In [38]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [40]:
df.columns=["1.Sütun","2.Sütun","3.Sütun"]
df

1.Sütun  2.Sütun  3.Sütun
0       19       12       16
1       21        1        0
2       16        4       22
3       16        0       10

In [41]:
#satır ve sütun bilgisi verir
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['1.Sütun', '2.Sütun', '3.Sütun'], dtype='object')]

In [42]:
df.ndim

2

In [43]:
df.shape

(4, 3)

In [44]:
df.values

array([[19, 12, 16],
       [21,  1,  0],
       [16,  4, 22],
       [16,  0, 10]])

In [45]:
#Bir sözlükten DataFrame oluşturalım
a = np.random.randint(10,size=5)
b = np.random.randint(10,size=5)
c = np.random.randint(10,size=5)
print(a)
print(b)
print(c)

[1 6 3 5 7]
[6 5 4 6 2]
[6 7 8 7 1]


In [46]:
sozluk2 = {"Col1":a,"Col2":b,"Col3":c}
sozluk2

{'Col1': array([1, 6, 3, 5, 7]),
 'Col2': array([6, 5, 4, 6, 2]),
 'Col3': array([6, 7, 8, 7, 1])}

In [47]:
data = pd.DataFrame(sozluk2)
data

Col1  Col2  Col3
0     1     6     6
1     6     5     7
2     3     4     8
3     5     6     7
4     7     2     1

In [48]:
data[0:3]

Col1  Col2  Col3
0     1     6     6
1     6     5     7
2     3     4     8

In [49]:
data[1:-1]

Col1  Col2  Col3
1     6     5     7
2     3     4     8
3     5     6     7

In [50]:
data[::2]

Col1  Col2  Col3
0     1     6     6
2     3     4     8
4     7     2     1

In [51]:
data[1:4][["Col1","Col3"]]

Col1  Col3
1     6     7
2     3     8
3     5     7

In [52]:
data[0:3]["Col2"]

0    6
1    5
2    4
Name: Col2, dtype: int32

In [53]:
data[0:3][["Col2"]]

Col2
0     6
1     5
2     4

In [54]:
data[["Col1","Col3"]]

Col1  Col3
0     1     6
1     6     7
2     3     8
3     5     7
4     7     1

In [55]:
data[["Col2"]]

Col2
0     6
1     5
2     4
3     6
4     2

In [56]:
#Silme işlemi için drop kullanılır.
data

Col1  Col2  Col3
0     1     6     6
1     6     5     7
2     3     4     8
3     5     6     7
4     7     2     1

In [57]:
data.drop(1,axis=0)

Col1  Col2  Col3
0     1     6     6
2     3     4     8
3     5     6     7
4     7     2     1

In [58]:
data

Col1  Col2  Col3
0     1     6     6
1     6     5     7
2     3     4     8
3     5     6     7
4     7     2     1

In [59]:
#İşlemin kalıcı olması için inplace True yapılmalı
data.drop(1,axis=0,inplace=True)

In [60]:
data

Col1  Col2  Col3
0     1     6     6
2     3     4     8
3     5     6     7
4     7     2     1

In [61]:
new_data = data.drop("Col2",axis=1)
new_data

Col1  Col3
0     1     6
2     3     8
3     5     7
4     7     1

In [62]:
data

Col1  Col2  Col3
0     1     6     6
2     3     4     8
3     5     6     7
4     7     2     1

In [63]:
#Yeni bir sütun eklemek
data["Col4"] = data["Col1"]/data["Col2"]
data

Col1  Col2  Col3      Col4
0     1     6     6  0.166667
2     3     4     8  0.750000
3     5     6     7  0.833333
4     7     2     1  3.500000

In [64]:
seri2

a    45
b    55
c    10
d    55
e    37
f    32
dtype: int32

In [65]:
data2=pd.DataFrame(seri2)
data2

0
a  45
b  55
c  10
d  55
e  37
f  32

**Değişken Seçimi: loc & iloc**

**loc:** Etikete dayalı seçme işlemi gerçekleştirir. Seçmek istediğimiz satır ve sütunun adını belirtmek gerekir. Seçimlerde verilen aralığın son elemanını içerir.

[satır_adı,sütun_adı]

**iloc:** İndexe dayalı seçme işlemidir. Seçmek istenilen satur ve sütunun indexi belirtilir. Indexe dayalı bir yöntem olduğundan belirtilen aralığın son öğesini içermez.

[satır_indexi,sütun_indexi]

In [66]:
numbers = np.random.randint(40,size=(10,3))
numbers

array([[ 6, 39, 16],
       [ 3, 14, 19],
       [34,  7, 13],
       [34,  3, 29],
       [33, 16, 30],
       [29, 32,  0],
       [10,  2, 31],
       [ 0, 34,  2],
       [10, 37, 21],
       [15, 17, 16]])

In [67]:
df = pd.DataFrame(numbers,columns=["Col1","Col2","Col3"])
df

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0
6    10     2    31
7     0    34     2
8    10    37    21
9    15    17    16

In [68]:
df.loc[0,"Col3"]

16

In [69]:
df.iloc[0,2]

16

In [70]:
df.loc[6,"Col2"]

2

In [71]:
df.iloc[6,1]

2

In [72]:
df.loc[2:8,"Col2":"Col3"]

Col2  Col3
2     7    13
3     3    29
4    16    30
5    32     0
6     2    31
7    34     2
8    37    21

In [73]:
df.iloc[2:9,1:3]

Col2  Col3
2     7    13
3     3    29
4    16    30
5    32     0
6     2    31
7    34     2
8    37    21

In [74]:
df.loc[0:5]

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0

In [75]:
df.loc[2:7]

Col1  Col2  Col3
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0
6    10     2    31
7     0    34     2

In [76]:
df.loc[2:7,"Col2"]

2     7
3     3
4    16
5    32
6     2
7    34
Name: Col2, dtype: int32

In [77]:
#########

In [78]:
df

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0
6    10     2    31
7     0    34     2
8    10    37    21
9    15    17    16

In [79]:
df["Col1"]>20

0    False
1    False
2     True
3     True
4     True
5     True
6    False
7    False
8    False
9    False
Name: Col1, dtype: bool

In [80]:
df[df["Col1"]>20]

Col1  Col2  Col3
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0

In [81]:
df[df["Col1"]>20][["Col1"]]

Col1
2    34
3    34
4    33
5    29

In [82]:
df[df["Col3"]<30]

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
5    29    32     0
7     0    34     2
8    10    37    21
9    15    17    16

In [83]:
df[df["Col3"]<30][["Col3"]]

Col3
0    16
1    19
2    13
3    29
5     0
7     2
8    21
9    16

In [84]:
df[df["Col3"]<30][["Col2","Col3"]]

Col2  Col3
0    39    16
1    14    19
2     7    13
3     3    29
5    32     0
7    34     2
8    37    21
9    17    16

In [85]:
df[(df["Col2"]>20) & (df["Col3"]<30)]

Col1  Col2  Col3
0     6    39    16
5    29    32     0
7     0    34     2
8    10    37    21

In [86]:
#join ile birleştirme işlemi yapılır
df

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0
6    10     2    31
7     0    34     2
8    10    37    21
9    15    17    16

In [87]:
df2 = df+50
df2

Col1  Col2  Col3
0    56    89    66
1    53    64    69
2    84    57    63
3    84    53    79
4    83    66    80
5    79    82    50
6    60    52    81
7    50    84    52
8    60    87    71
9    65    67    66

In [88]:
pd.concat([df,df2])

Col1  Col2  Col3
0     6    39    16
1     3    14    19
2    34     7    13
3    34     3    29
4    33    16    30
5    29    32     0
6    10     2    31
7     0    34     2
8    10    37    21
9    15    17    16
0    56    89    66
1    53    64    69
2    84    57    63
3    84    53    79
4    83    66    80
5    79    82    50
6    60    52    81
7    50    84    52
8    60    87    71
9    65    67    66

In [89]:
pd.concat([df,df2],ignore_index=True)

Col1  Col2  Col3
0      6    39    16
1      3    14    19
2     34     7    13
3     34     3    29
4     33    16    30
5     29    32     0
6     10     2    31
7      0    34     2
8     10    37    21
9     15    17    16
10    56    89    66
11    53    64    69
12    84    57    63
13    84    53    79
14    83    66    80
15    79    82    50
16    60    52    81
17    50    84    52
18    60    87    71
19    65    67    66

In [90]:
df2.columns=["Col1","Col2","Col4"]
df2

Col1  Col2  Col4
0    56    89    66
1    53    64    69
2    84    57    63
3    84    53    79
4    83    66    80
5    79    82    50
6    60    52    81
7    50    84    52
8    60    87    71
9    65    67    66

In [91]:
pd.concat([df,df2])

Col1  Col2  Col3  Col4
0     6    39  16.0   NaN
1     3    14  19.0   NaN
2    34     7  13.0   NaN
3    34     3  29.0   NaN
4    33    16  30.0   NaN
5    29    32   0.0   NaN
6    10     2  31.0   NaN
7     0    34   2.0   NaN
8    10    37  21.0   NaN
9    15    17  16.0   NaN
0    56    89   NaN  66.0
1    53    64   NaN  69.0
2    84    57   NaN  63.0
3    84    53   NaN  79.0
4    83    66   NaN  80.0
5    79    82   NaN  50.0
6    60    52   NaN  81.0
7    50    84   NaN  52.0
8    60    87   NaN  71.0
9    65    67   NaN  66.0

In [92]:
#ikisinde de ortak olan sütunları birleştirir
pd.concat([df,df2],join="inner")

Col1  Col2
0     6    39
1     3    14
2    34     7
3    34     3
4    33    16
5    29    32
6    10     2
7     0    34
8    10    37
9    15    17
0    56    89
1    53    64
2    84    57
3    84    53
4    83    66
5    79    82
6    60    52
7    50    84
8    60    87
9    65    67

In [93]:
pd.concat([df,df2],axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0     6    39    16    56    89    66
1     3    14    19    53    64    69
2    34     7    13    84    57    63
3    34     3    29    84    53    79
4    33    16    30    83    66    80
5    29    32     0    79    82    50
6    10     2    31    60    52    81
7     0    34     2    50    84    52
8    10    37    21    60    87    71
9    15    17    16    65    67    66

In [2]:
####################
import pandas as pd

In [3]:
data = pd.DataFrame({"Öğrenciler":["Ayşe","Mehmet","Fatma","Fatma","Mehmet","Ayşe","Ayşe","Fatma","Mehmet"],
                   "Dersler":["Matematik","Türkçe","Türkçe","Fen Bilgisi","Matematik","Fen Bilgisi","Türkçe","Matematik","Fen Bilgisi"],
                    "Puan":[80,75,92,78,64,84,73,94,90]})

data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [5]:
data[["Dersler"]][data["Öğrenciler"]=="Ayşe"]

Dersler
0    Matematik
5  Fen Bilgisi
6       Türkçe

In [96]:
data2 = pd.DataFrame({"Öğretmenler":["Selin","Furkan","Emine"],
                   "Dersler":["Matematik","Türkçe","Fen Bilgisi"]})
data2

Öğretmenler      Dersler
0       Selin    Matematik
1      Furkan       Türkçe
2       Emine  Fen Bilgisi

In [97]:
pd.merge(data,data2)

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [99]:
new_data = pd.merge(data,data2,on="Dersler")
new_data

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [100]:
data["Öğrenciler"]

0      Ayşe
1    Mehmet
2     Fatma
3     Fatma
4    Mehmet
5      Ayşe
6      Ayşe
7     Fatma
8    Mehmet
Name: Öğrenciler, dtype: object

In [101]:
data[["Öğrenciler"]]

Öğrenciler
0       Ayşe
1     Mehmet
2      Fatma
3      Fatma
4     Mehmet
5       Ayşe
6       Ayşe
7      Fatma
8     Mehmet

In [102]:
#Ayşenin ders ve puanına bakalım
data[data["Öğrenciler"]=="Ayşe"]

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73

In [103]:
data[data["Öğrenciler"]=="Mehmet"]

Öğrenciler      Dersler  Puan
1     Mehmet       Türkçe    75
4     Mehmet    Matematik    64
8     Mehmet  Fen Bilgisi    90

In [104]:
data[data["Öğrenciler"]=="Mehmet"][["Dersler","Puan"]]

Dersler  Puan
1       Türkçe    75
4    Matematik    64
8  Fen Bilgisi    90

In [105]:
data[data["Dersler"]=="Matematik"]

Öğrenciler    Dersler  Puan
0       Ayşe  Matematik    80
4     Mehmet  Matematik    64
7      Fatma  Matematik    94

In [106]:
data[data["Dersler"]=="Fen Bilgisi"]

Öğrenciler      Dersler  Puan
3      Fatma  Fen Bilgisi    78
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90

In [107]:
data[data["Dersler"]=="Fen Bilgisi"][["Öğrenciler","Puan"]]

Öğrenciler  Puan
3      Fatma    78
5       Ayşe    84
8     Mehmet    90

In [108]:
data[data["Puan"]>80]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [109]:
data[(data["Dersler"] =="Matematik") & (data["Puan"]>80)]

Öğrenciler    Dersler  Puan
7      Fatma  Matematik    94

In [110]:
data[(data["Dersler"] =="Türkçe") & (data["Puan"]<85)]

Öğrenciler Dersler  Puan
1     Mehmet  Türkçe    75
6       Ayşe  Türkçe    73